// Copies the version out of the CLI into a constant the worker can serve
// instantly. The CLI stays the single source of truth; this is just a mirror.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const cli = readFileSync(join(here, "..", "..", "magiccode"), "utf8");
const version = cli.match(/^const VERSION = "([^"]+)";/m)?.[1];

if (!version) {
  console.error("sync-version: could not find VERSION in ../magiccode");
  process.exit(1);
}

writeFileSync(
  join(here, "..", "app", "version", "version.generated.ts"),
  `// Generated by scripts/sync-version.mjs — do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`
);
console.log(`sync-version: ${version}`);
